account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PwdResetForm ,RwdResetConfirmForm
from django.views.generic import TemplateView

app_name = 'account'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='account/registration/login.html',form_class=UserLoginForm),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/account/login/'),name='logout'),
    path('register/', views.account_register,name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/',views.account_activate,name='activate'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='account/user/password_reset_form.html',
                                                                success_url='password_reset_email_confirm',
                                                                email_template_name='account/user/password_reset_email.html',
                                                                form_class=PwdResetForm),name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete',
                                                                                                form_class=RwdResetConfirmForm),name='password_reset_confirm'),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    path('dashboard/', views.dashboard,name='dashboard'),
    path('profile/edit/',views.edit_details,name='edit_details'),
    path('profile/delete/',views.delete_user,name='delete_user'),
    path('profile/delete_confirm/',TemplateView.as_view(template_name='account/user/delete_confirm.html'),name='delete_confirm'),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path('wishlist/',views.wishlist,name="wishlist"),
     path('wishlist/add_to_wishlist/<int:id>/',views.add_to__wishlist,name='user_wishlist'),
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary,name="basket_summary"),
    path('add/',views.basket_add,name="basket_add"),
    path('delete/',views.basket_delete,name="basket_delete"),
    path('update/', views.basket_update, name='basket_update'),
]

chat/urls.py
from django.urls import path
from . import views

app_name="chat"

urlpatterns = [
    path('chat/', views.index,name="chat")
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('products/',views.product_list,name='products'),
    path('products/<slug:slug>',views.product_detail,name="products_detail"),
    path('category/<slug:category_slug>',views.category_detail,name="category_detail"),
]

shop/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey 
from django.utils.translation import gettext_lazy as _
from config.settings.base import AUTH_USER_MODEL
# Create your models here.

class Category(MPTTModel):
    name = models.CharField(verbose_name=_('Category name'),help_text=_('Required and unique'),max_length=150,unique=True)
    slug = models.SlugField(verbose_name=_('Category safe URL'),max_length=150,unique=True)
    parent = TreeForeignKey('self',related_name='children',null=True,on_delete=models.SET_NULL,blank=True)
    img = models.ImageField(upload_to='categories/',blank=True)
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def get_absolute_url(self):
        return reverse("shop:category_detail", kwargs={"category_slug": self.slug})
    

    def __str__(self):
        return self.name
    
class ProductType(models.Model):
    name = models.CharField(verbose_name=_('Product type'),help_text=_('Required'),max_length=150,unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('Product type')
        verbose_name_plural = _('Product types')

    def __str__(self):
        return self.name

class ProductSpecification(models.Model):
    product_type = models.ForeignKey(ProductType,on_delete=models.RESTRICT) 
    name = models.CharField(verbose_name=_('Name'),help_text=_('Required'),max_length=150)

    class Meta:
        verbose_name = _('Product Specification')
        verbose_name_plural = _('ProductSpecifications')

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.SET_NULL,null=True)
    product_type = models.ForeignKey(ProductType,on_delete=models.RESTRICT) 
    title = models.CharField(verbose_name=_('Title'),help_text=_('Required'),max_length=150)
    slug = models.SlugField(max_length=200, db_index=True)
    #image = models.ForeignKey('ProductImage',related_name='product_image',on_delete=models.SET_DEFAULT)
    description = models.TextField(verbose_name=_('Description'),help_text=_('Not Required'),blank=True)
    regular_price = models.DecimalField(verbose_name=_('Regular price'),help_text=('Maximum 999999.9'),error_messages={
        "name":{
            "max_length":_('The price must be between 0 and 999999.9'),
        },
    },max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(verbose_name=_('Discount price'),help_text=('Maximum 999999.9'),error_messages={
        "name":{
            "max_length":_('The price must be between 0 and 999999.9'),
        },
    },max_digits=10, decimal_places=2)
    is_active = models.BooleanField(verbose_name=_('Product visibility'),help_text=_('Change product visibility'),default=True)
    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True)
    user_wishlist = models.ManyToManyField(AUTH_USER_MODEL,related_name='wishlist',blank=True)
    

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("shop:products_detail", kwargs={"slug": self.slug})
    

    def __str__(self):
        return self.title

class ProductSpecificationValue(models.Model):
    product = models.ForeignKey(Product,related_name='products',on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification,related_name='specification',on_delete=models.RESTRICT)
    value = models.CharField(verbose_name=_('Value'),help_text=_('Product Specification Value'),max_length=255)

    class Meta:
        verbose_name = _('Product Specification Value')
        verbose_name_plural = _('Product Specification Values')

    def __str__(self):
        return self.value

class ProductImage(models.Model):
    product = models.ForeignKey(Product,related_name='product',on_delete=models.CASCADE)
    image = models.ImageField(verbose_name = _("Image"),help_text=_('Upload a product image'), upload_to='products/%Y/%m/%d',default="products/default-image.jpg")
    alt_text = models.CharField(verbose_name=_('Alternative image text'),help_text=_('Please add alternative image text'),null=True,blank=True,max_length=250)
    is_feature = models.BooleanField(default=False)
    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True,editable=False)

    class Meta:
        verbose_name = _('Product Image')
        verbose_name_plural = _('Product Images')
    
class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    message = models.TextField(max_length=500) 
    product = models.ForeignKey(Product,related_name='comment',on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product,Comment
from django.views.generic import ListView,DetailView

# Create your views here.

""" class ProductListView(ListView):
    model = Product
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.product.get_queryset() """

def product_list(request):
    products = Product.objects.prefetch_related("product").filter(is_active=True)
    return render(request,'shop/product_list.html',{'product_list':products})
    


def product_detail(request,slug):
    product_detail = get_object_or_404(Product,slug=slug,is_active = True)
    return render(request,'shop/products/single_product.html',{'product':product_detail})
    
def category_detail(request,category_slug):
    category_detail = get_object_or_404(Category,slug=category_slug)
    product = Product.objects.filter(category__in=Category.objects.get(name=category_slug).get_descendants(include_self=True))
    return render(request,'shop/products/category.html',{'category':category_detail,'products':product})

templates/shop/products/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="container">
    <div class="row">
      <div class="album py-5">


        <div class="pb-3"><h1 class="h3">{{ category.name }}</h1></div>
        <hr>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

          {% for product in products %}

          <div class="col">
            <div class="card border-0">
              {% for image in product.product.all %}
              {% if image.is_feature %}
              <img class="img-fluid" alt="{{ image.image.alt_text }}" src="{{ image.image.url }}">
              {% endif %}
              {% endfor %}
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">£{{product.regular_price}}</small>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </div>

  </div>


</main>

{% endblock %}

templates/shop/products/single_product.html
{% extends "base.html" %}
{% load static %}
{% block stylesheet %}{% static 'css/shop/shop.css' %}{% endblock %}
{% block title %}
{% if product %}{{ product.title }}{% else %}Product{% endif %}
{% endblock %}
{% block content %}

<div class="container">
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }}" role="alert">
{% for message in messages  %}
  {{message|safe}} - <a href="{% url "account:wishlist" %}" class="alert-link">Your Wishlist</a>.
{% endfor %}
</div>
{% endif %}
  <div class="row g-3">
    <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
      <div class="d-grid gap-2">
        <div class="d-flex d-flex-inline justify-content-between">
          <div><span class="h3">£{{ product.regular_price }}</span>
            <p class="text-muted">includes tax</p>
          </div>
          <div>
            <label for="select">Qty</label>
            <select id="select" class="h6 store-select-dropdown">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
          </div>
        </div>
        <hr>
        <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
          basket</button>
        <a href="{% url "account:user_wishlist" product.id  %}" class="btn btn-light fw500" role="button" aria-disabled="true">Add to Wish List</a>
      </div>
    </div>
    <div class="col-md-7 col-lg-7 p-0">
      <div class="card mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-12">
            <div class="card-body p-1">
              <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
              <div class="bg-light">

                {% for image in product.product.all %}
                {% if image.is_feature %}
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ image.image.url }}"
                  alt="{{ image.image.alt_text }}">
                {% else %}
                <img class="img-fluid d-block-inline pt-3" width="100px" alt="Responsive image"
                  src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                {% endif %}
                {% endfor %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    $(document).on('click', '#add-button', function (e) {
      e.preventDefault();
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_add" %}',
        data: {
          productid: $('#add-button').val(),
          productqty: $('#select option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          document.getElementById("basket-qty").innerHTML = json.qty
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  </script>

  {% endblock %}